### ISSUE TITLE
Status of cross-platform

### ISSUE THREAD

**Issue by LeqitDev** [CubesCoders/crust-gui#2]
Test on multiple linux systems.
Test on MacOS.

**Comment by LeqitDev** [comment]
Not yet functioning on linux (Fedora)
See #1

**Comment by eademir** [comment]
<img width="1728" alt="Screenshot 2023-08-16 at 07 17 40" src="https://github.com/CubesCoders/crust-gui/assets/36801647/7dd71053-3f86-43ec-8cc6-c1554842ab91">

on MacOS 13.5 arm build, though, I could not test create, delete, etc. Also, when I clicked the button on the right side, I got "thread 'main' panicked at 'byte index 2 is out of bounds of `/`', /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/str/mod.rs:671:13"

**Comment by LeqitDev** [comment]
Thanks for testing the problem should now be solved. There is still an error with selecting the workspace path i will look into it.

**Comment by eademir** [comment]
Problem is solved for MacOS. Thank you.

**Comment by LeqitDev** [comment]
I tested it on Ubuntu 20.04.5 WSL it worked. Closing this issue...
If somebody has problems related to this issue please reopen.
